Repository southworks/consul, pull requests merged in 2022-10, with the labels that each got.

#76 [CONSUL-504] Replace docker run in docker_consul function
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#78 [CONSUL-399] Update envoy to 1.23.1
  build-support-windows/build-consul-dev-image.sh
  build-support-windows/build-consul-local-images.sh
  execute_windows_tests.sh
  test/integration/connect/envoy/Dockerfile-consul-envoy-windows
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#79 [CONSUL-510] Support case-wanfed-gw on Windows
  execute_windows_tests.sh
  test/integration/connect/envoy/case-wanfed-gw/global-setup-windows.sh
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#80 [CONSUL-506] Update troubleshooting Documentation
  test/integration/connect/envoy/WindowsTroubleshooting.md
  test/integration/connect/envoy/case-cfg-resolver-svc-failover/verify.bats
Labels: documentation

#81 [CONSUL-512] Review debug_dump_volumes Function
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#82 [CONSUL-514] Add zipkin to Docker Image
  build-support-windows/Dockerfile-consul-local-windows
  build-support-windows/Dockerfile-openzipkin-windows
Labels: docker

#83 [CONSUL-515] Update Documentation
  build-support-windows/BUILD-IMAGES.md
  test/integration/connect/envoy/WindowsTroubleshooting.md
Labels: documentation
