Repository southworks/consul, pull requests merged in 2022-07, with the labels that each got.

#1 [CONSUL-167] Create windows image with Socat precompiled
  test/integration/connect/envoy/Dockerfile-socat-windows
  test/integration/connect/envoy/docker.windows.md
Labels: enhancement

#5 [CONSUL-175] Update Environment variable declaration
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/main_test.go
  test/integration/connect/envoy/run-tests.windows.sh
Labels: enhancement

#8 [CONSUL-183] Create Bats Dockerfile
  test/integration/connect/envoy/Dockerfile-bats-core-windows
  test/integration/connect/envoy/Dockerfile-bats-windows
  test/integration/connect/envoy/case-dummy-bats/dummy-function.bash
  test/integration/connect/envoy/case-dummy-bats/setup.sh
  test/integration/connect/envoy/case-dummy-bats/vars.sh
  test/integration/connect/envoy/case-dummy-bats/verify_1.bats
  test/integration/connect/envoy/case-dummy-bats/verify_2.bats
  test/integration/connect/envoy/docker.windows.md
Labels: docker

#10 [CONSUL-207] Move base Dockerfiles to release folder
  build-support-windows/Dockerfile-bats-core-windows
  build-support-windows/Dockerfile-fortio-windows
  build-support-windows/Dockerfile-socat-windows
  build-support-windows/build-images.sh
  build-support-windows/docker.windows.md
  test/integration/connect/envoy/docker.windows.md
  test/integration/connect/envoy/run-tests.windows.sh
Labels: enhancement

#15 [CONSUL-210] Run Bats test and verify sh script path
  build-support-windows/Dockerfile-bats-core-windows
  test/integration/connect/envoy/case-dummy-bats/verify_2.bats
  test/integration/connect/envoy/docker.windows.md
Labels: docker

#14 [CONSUL-190] Support consul windows compilation in Docker
  .release/docker/docker-entrypoint-windows.sh
  Dockerfile-windows
  build-support-windows/Dockerfile-consul-dev-windows
  build-support-windows/Dockerfile-consul-dev-windows.sh
  build-support-windows/build-images.sh
  build-support-windows/docker.windows.md
  build-support/docker/Consul-Dev-windows.compile.sh
Labels: docker

#13 [CONSUL-145] Support windows consul-envoy from envoyproxy/envoy
  test/integration/connect/envoy/Dockerfile-consul-envoy-windows
  test/integration/connect/envoy/Dockerfile-test-sds-server-windows
  test/integration/connect/envoy/docker.windows.md
Labels: docker

#17 [CONSUL-212] Create/update dummy test case using jq or curl as output
  test/integration/connect/envoy/Dockerfile-bats-windows
  test/integration/connect/envoy/case-dummy-bats/dummy-function.bash
  test/integration/connect/envoy/case-dummy-bats/verify_2.bats
  test/integration/connect/envoy/docker.windows.md
Labels: docker, script

#18 [CONSUL-176] Support replacing CRLF by LF on scenarios scripts
  build-support-windows/docker.windows.md
  test/integration/connect/envoy/main_test.go
Labels: script

#16 [CONSUL-214] Update run-tests.windows.sh
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#20 [CONSUL-242] Create Jaeger Windows Image
  build-support-windows/Dockerfile-jaegertracing-windows
  build-support-windows/build-images.sh
  build-support-windows/docker.windows.md
  test/integration/connect/envoy/run-tests.windows.sh
Labels: docker

#22 [CONSUL-238] Create Openzipkin Dockerfile
  build-support-windows/Dockerfile-openzipkin-windows
  build-support-windows/build-images.sh
  build-support-windows/docker.windows.md
  test/integration/connect/envoy/run-tests.windows.sh
Labels: docker

#21 [CONSUL-220] Envoy Tests | Scripts | Docker Network snippet
  build-support-windows/build-images.sh
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/main_test.go
  test/integration/connect/envoy/run-tests.windows.sh
Labels: docker, script

#24 [CONSUL-250] Build/tag Kubernetes/pause image
  build-support-windows/build-images.sh
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#25 [CONSUL-245] Main readme file
  WINDOWS-TEST.md
  build-support-windows/BUILD-IMAGES.md
  test/integration/connect/envoy/docker.windows.md
Labels: documentation

#23 [CONSUL-246] Scenario case-badauthz
  Dockerfile-windows
  build-support-windows/Dockerfile-fortio-windows
  test/integration/connect/envoy/Dockerfile-consul-envoy-windows
  test/integration/connect/envoy/consul-windows-base-cfg/base.hcl
  test/integration/connect/envoy/consul-windows-base-cfg/service_s1.hcl
  test/integration/connect/envoy/consul-windows-base-cfg/service_s2.hcl
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script
