Repository southworks/consul, pull requests merged in 2022-09, with the labels that each got.

#37 [CONSUL-350] POC Single container proposal
  Dockerfile-windows
  build-support-windows/Dockerfile-consul-dev-windows
  build-support-windows/build-images.sh
  test/integration/connect/envoy/Dockerfile-bats-windows
  test/integration/connect/envoy/case-badauthz/setup.sh
  test/integration/connect/envoy/consul-windows-base-cfg/envoy/s1-bootstrap.json
  test/integration/connect/envoy/consul-windows-base-cfg/envoy/s2-bootstrap.json
  test/integration/connect/envoy/consul-windows-base-cfg/service_s1.hcl
  test/integration/connect/envoy/consul-windows-base-cfg/service_s2.hcl
  test/integration/connect/envoy/docs/img/consul-all-green.png
  test/integration/connect/envoy/docs/img/hostport-change.png
  test/integration/connect/envoy/docs/img/run-test.png
  test/integration/connect/envoy/docs/img/windows-arch-proposal.png
  test/integration/connect/envoy/docs/img/windows-container-actual.png
  test/integration/connect/envoy/docs/img/windows-container-proposal.png
  test/integration/connect/envoy/docs/windows_proposal.md
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: documentation, script

#39 [CONSUL-394] Run Fortio and Envoy in single container
  build-support-windows/Dockerfile-consul-dev-windows
  test/integration/connect/envoy/consul-windows-base-cfg/envoy/s1-bootstrap.json
  test/integration/connect/envoy/consul-windows-base-cfg/envoy/s2-bootstrap.json
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#40 [CONSUL-395] Update check_hostport and Usage
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#41 [CONSUL-397] Copy envoy binary from Image
  Dockerfile-windows
  build-support-windows/Dockerfile-consul-dev-windows
  test/integration/connect/envoy/Dockerfile-bats-windows
Labels: docker

#43 [CONSUL-382] Support openssl in unique test dockerfile
  build-support-windows/Dockerfile-consul-dev-windows
Labels: docker

#44 [CONSUL-405] Add bats to single container
  build-support-windows/Dockerfile-consul-dev-windows
  execute_test.sh
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: docker, script

#46 [CONSUL-414] Run Prometheus Test Cases and Validate Changes
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#45 [CONSUL-410] Run Jaeger in Single container
  build-support-windows/Dockerfile-consul-dev-windows
  test/integration/connect/envoy/case-zipkin/verify.bats
  test/integration/connect/envoy/run-tests.windows.sh
Labels: docker, script

#51 [CONSUL-417] Update Documentation Single Container Dockerfile
  execute_test.sh
  test/integration/connect/envoy/docs/single-container.md
Labels: documentation, theme/cli, theme/envoy/xds, theme/telemetry, type/docs

#54 [CONSUL-428] Add Socat to Single Container
  build-support-windows/Dockerfile-consul-local-windows
  build-support-windows/build-images.sh
Labels: docker

#52 [CONSUL-424] Replace pkill in kill_envoy function
  build-support-windows/BUILD-IMAGES.md
  build-support-windows/Dockerfile-consul-dev-windows
  build-support-windows/Dockerfile-consul-dev-windows.sh
  build-support-windows/Dockerfile-consul-local-windows
  build-support-windows/build-images.sh
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#53 [CONSUL-434] Replace Docker run functions in Helpers bash script
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#55 [CONSUL-435] Replace docker run in set_ttl_check_state & wait_for_agent_service_register functions
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#56 [CONSUL-438] Add netcat (nc) in the Single container Dockerfile
  build-support-windows/BUILD-IMAGES.md
  build-support-windows/Dockerfile-consul-local-windows
  build-support-windows/Dockerfile-socat-windows
Labels: docker

#57 [CONSUL-429] Replace Docker run with Docker exec in run_container_fake-statsd Function
  build-support-windows/Dockerfile-consul-local-windows
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#58 [CONSUL-436] Curl timeout and run tests
  test/integration/connect/envoy/case-zipkin/verify.bats
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#59 [CONSUL-443] Create dogstatsd Function
  test/integration/connect/envoy/case-dogstatsd-udp/verify.bats
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#60 [CONSUL-431] Update Docs Netcat
  test/integration/connect/envoy/docs/single-container.md
Labels: documentation

#61 [CONSUL-439] Parse nc Command in retry Function
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#63 [CONSUL-463] Review curl Exec and get_ca_root Func
  test/integration/connect/envoy/case-ingress-gateway-tls/verify.bats
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#64 [CONSUL-453] Docker hostname in Helper functions for XDS_TARGET=client
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#66 [CONSUL-461] Test Wipe Volumes Without Extra Container
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#65 [CONSUL-454] Check ports in the Server and Agent containers
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#62 [CONSUL-441] Update windows dockerfile with version
  Dockerfile-windows
  build-support-windows/BUILD-IMAGES.md
  build-support-windows/Dockerfile-consul-dev-windows
  build-support-windows/Dockerfile-consul-local-windows
  build-support-windows/Dockerfile-consul-local-windows.sh
  build-support-windows/Dockerfile-openzipkin-windows
  build-support-windows/build-consul-dev-image.sh
  build-support-windows/build-consul-local-images.sh
  build-support-windows/build-images.sh
  build-support-windows/build-test-sds-server-image.sh
  execute_windows_tests.sh
  test/integration/connect/envoy/Dockerfile-consul-envoy-windows
  test/integration/connect/envoy/Dockerfile-test-sds-server-windows
  test/integration/connect/envoy/case-dummy-bats/dummy-function.bash
  test/integration/connect/envoy/case-dummy-bats/setup.sh
  test/integration/connect/envoy/case-dummy-bats/vars.sh
  test/integration/connect/envoy/case-dummy-bats/verify_1.bats
  test/integration/connect/envoy/case-dummy-bats/verify_2.bats
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: docker, script

#67 [CONSUL-466] Review case-grpc Failing Test
  test/integration/connect/envoy/case-grpc/service_s1.hcl
  test/integration/connect/envoy/case-grpc/verify.bats
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#68 [CONSUL-494] Review case-cfg-resolver-svc-failover
  test/integration/connect/envoy/case-cfg-resolver-svc-failover/verify.bats
Labels: script

#69 [CONSUL-496] Replace docker_wget & docker_curl with docker_exec
  test/integration/connect/envoy/helpers.windows.bash
Labels: script

#70 [CONSUL-499] Cleanup Scripts - Remove nanoserver
  test/integration/connect/envoy/consul-windows-base-cfg/base.hcl
  test/integration/connect/envoy/consul-windows-base-cfg/service_s1.hcl
  test/integration/connect/envoy/consul-windows-base-cfg/service_s2.hcl
  test/integration/connect/envoy/helpers.windows.bash
  test/integration/connect/envoy/run-tests.windows.sh
Labels: script

#72 [CONSUL-500] Update Troubleshooting Documentation
  test/integration/connect/envoy/WindowsTroubleshooting.md
Labels: documentation
